--28796527, Joleen Tang

SET ECHO ON
SPOOL fdas_schema_output.txt
-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-10-14 14:40:42 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE ass_emp_history CASCADE CONSTRAINTS;

DROP TABLE assessor CASCADE CONSTRAINTS;

DROP TABLE build_dam_visit CASCADE CONSTRAINTS;

DROP TABLE building CASCADE CONSTRAINTS;

DROP TABLE fe_build_damage CASCADE CONSTRAINTS;

DROP TABLE fire_event CASCADE CONSTRAINTS;

DROP TABLE insurer CASCADE CONSTRAINTS;

DROP TABLE lga_fe CASCADE CONSTRAINTS;

DROP TABLE local_gov_area CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE property_type CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ass_emp_history (
    aeh_startdate  DATE NOT NULL,
    ass_id         VARCHAR2(4) NOT NULL,
    ins_code       VARCHAR2(9) NOT NULL,
    aeh_enddate    DATE
);

COMMENT ON COLUMN ass_emp_history.aeh_startdate IS
    'Date when assessor started working for particular insurance company';

COMMENT ON COLUMN ass_emp_history.ass_id IS
    'Unique identifer of assessor';

COMMENT ON COLUMN ass_emp_history.ins_code IS
    'Unique identifier that distinguishes insurance companies';

COMMENT ON COLUMN ass_emp_history.aeh_enddate IS
    'Date when assessor stopped working for particular insurance company';

ALTER TABLE ass_emp_history
    ADD CONSTRAINT ass_emp_history_pk PRIMARY KEY ( ass_id,
                                                    aeh_startdate,
                                                    ins_code );

CREATE TABLE assessor (
    ass_id         VARCHAR2(4) NOT NULL,
    ass_gname      VARCHAR2(20) NOT NULL,
    ass_fname      VARCHAR2(20) NOT NULL,
    ass_phoneno    VARCHAR2(10) NOT NULL,
    curr_ins_code  VARCHAR2(9) NOT NULL
);

COMMENT ON COLUMN assessor.ass_id IS
    'Unique identifer of assessor';

COMMENT ON COLUMN assessor.ass_gname IS
    'Assessor''s given name';

COMMENT ON COLUMN assessor.ass_fname IS
    'Assessor''s family name';

COMMENT ON COLUMN assessor.ass_phoneno IS
    'Assessor''s contact number';

COMMENT ON COLUMN assessor.curr_ins_code IS
    'Unique identifier that distinguishes insurance companies';

ALTER TABLE assessor ADD CONSTRAINT assessor_pk PRIMARY KEY ( ass_id );

CREATE TABLE build_dam_visit (
    febd_id              NUMBER(6) NOT NULL,
    bdv_datetime_arrive  DATE NOT NULL,
    bdv_datetime_depart  DATE
);

COMMENT ON COLUMN build_dam_visit.bdv_datetime_arrive IS
    'Date and time assessor arrived for building damage assessment visit';

COMMENT ON COLUMN build_dam_visit.bdv_datetime_depart IS
    'Date and time assessor departed after  building damage assessment visit';

ALTER TABLE build_dam_visit ADD CONSTRAINT build_dam_visit_pk PRIMARY KEY ( febd_id,
                                                                            bdv_datetime_arrive );

CREATE TABLE building (
    build_id           NUMBER(7) NOT NULL,
    prop_id            NUMBER(8) NOT NULL,
    build_no           NUMBER(3) NOT NULL,
    build_approv_date  DATE,
    build_size         NUMBER(8) NOT NULL,
    build_class        NUMBER(3) NOT NULL,
    build_lga_value    NUMBER(10, 2) NOT NULL,
    ins_code           VARCHAR2(9)
);

COMMENT ON COLUMN building.build_id IS
    'Unique identifier for every building across every property';

COMMENT ON COLUMN building.prop_id IS
    'Unique national property ID';

COMMENT ON COLUMN building.build_no IS
    'Building number identifier for buildings on a single property';

COMMENT ON COLUMN building.build_approv_date IS
    'Date on which the building was approved for construction';

COMMENT ON COLUMN building.build_size IS
    'The size of the building, in square meters';

COMMENT ON COLUMN building.build_class IS
    'National Construction Code Class of the building';

COMMENT ON COLUMN building.build_lga_value IS
    'LGA estimated value of the building, in dollars';

COMMENT ON COLUMN building.ins_code IS
    'Unique identifier that distinguishes insurance companies';

ALTER TABLE building ADD CONSTRAINT building_pk PRIMARY KEY ( build_id );

ALTER TABLE building ADD CONSTRAINT building_nk UNIQUE ( build_no,
                                                         prop_id );

CREATE TABLE fe_build_damage (
    febd_id             NUMBER(6) NOT NULL,
    fe_id               CHAR(9) NOT NULL,
    febd_dam_cost       NUMBER(10, 2) NOT NULL,
    febd_total_destroy  CHAR(1) NOT NULL,
    febd_ins_cov        CHAR(1) NOT NULL,
    build_id            NUMBER(7) NOT NULL,
    ass_id              VARCHAR2(4)
);

ALTER TABLE fe_build_damage
    ADD CONSTRAINT chk_total_destroy CHECK ( febd_total_destroy IN ( 'N', 'Y' ) );

ALTER TABLE fe_build_damage
    ADD CHECK ( febd_ins_cov IN ( 'N', 'Y' ) );

COMMENT ON COLUMN fe_build_damage.fe_id IS
    'Unique identifier of fire event';

COMMENT ON COLUMN fe_build_damage.febd_dam_cost IS
    'Building damage costs incurred by fire in dollars';

COMMENT ON COLUMN fe_build_damage.febd_total_destroy IS
    'Whether or not the building is totally destroyed';

COMMENT ON COLUMN fe_build_damage.febd_ins_cov IS
    'Whether or not the incurred fire damage is covered by insurance';

COMMENT ON COLUMN fe_build_damage.build_id IS
    'Unique identifier for every building across every property';

COMMENT ON COLUMN fe_build_damage.ass_id IS
    'Unique identifer of assessor';

ALTER TABLE fe_build_damage ADD CONSTRAINT fe_build_damage_pk PRIMARY KEY ( febd_id );

ALTER TABLE fe_build_damage ADD CONSTRAINT fe_build_damage_nk UNIQUE ( build_id,
                                                                       fe_id );

CREATE TABLE fire_event (
    fe_id            CHAR(9) NOT NULL,
    fe_name          VARCHAR2(30),
    fe_start_date    DATE NOT NULL,
    fe_start_lat     NUMBER(6, 4) NOT NULL,
    fe_start_long    NUMBER(7, 4) NOT NULL,
    fe_ha_burnt      NUMBER(9, 2) DEFAULT 0 NOT NULL,
    fe_lives_lost    NUMBER(5) DEFAULT 0 NOT NULL,
    fe_total_dam     NUMBER(10, 2) DEFAULT 0 NOT NULL,
    fe_started_from  CHAR(9)
);

COMMENT ON COLUMN fire_event.fe_id IS
    'Unique identifier of fire event';

COMMENT ON COLUMN fire_event.fe_name IS
    'Name of fire event';

COMMENT ON COLUMN fire_event.fe_start_date IS
    'Date when fire event started';

COMMENT ON COLUMN fire_event.fe_start_lat IS
    'Estimated start latitude of fire event';

COMMENT ON COLUMN fire_event.fe_start_long IS
    'Estimated start longitude of fire event';

COMMENT ON COLUMN fire_event.fe_ha_burnt IS
    'The number of hectares burnt in the given fire event';

COMMENT ON COLUMN fire_event.fe_lives_lost IS
    'Number of lives lost in fire event';

COMMENT ON COLUMN fire_event.fe_total_dam IS
    'Total costs of damage from fire event, in dollars';

COMMENT ON COLUMN fire_event.fe_started_from IS
    'Unique identifier of fire event';

ALTER TABLE fire_event ADD CONSTRAINT fire_event_pk PRIMARY KEY ( fe_id );

CREATE TABLE insurer (
    ins_code     VARCHAR2(9) NOT NULL,
    ins_name     VARCHAR2(30) NOT NULL,
    ins_phoneno  VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN insurer.ins_code IS
    'Unique identifier that distinguishes insurance companies';

COMMENT ON COLUMN insurer.ins_name IS
    'Name of insurance company';

COMMENT ON COLUMN insurer.ins_phoneno IS
    'Insurance company phone number';

ALTER TABLE insurer ADD CONSTRAINT insurer_pk PRIMARY KEY ( ins_code );

CREATE TABLE lga_fe (
    lga_code  NUMBER(3) NOT NULL,
    fe_id     CHAR(9) NOT NULL
);

COMMENT ON COLUMN lga_fe.lga_code IS
    'Unique code identifying a local government area';

COMMENT ON COLUMN lga_fe.fe_id IS
    'Unique identifier of fire event';

ALTER TABLE lga_fe ADD CONSTRAINT lga_fe_pk PRIMARY KEY ( fe_id,
                                                          lga_code );

CREATE TABLE local_gov_area (
    lga_code        NUMBER(3) NOT NULL,
    lga_name        VARCHAR2(30) NOT NULL,
    lga_size_ha     NUMBER(8, 2) NOT NULL,
    lga_ceo_name    VARCHAR2(50) NOT NULL,
    lga_bf_phoneno  CHAR(10) NOT NULL
);

COMMENT ON COLUMN local_gov_area.lga_code IS
    'Unique code identifying a local government area';

COMMENT ON COLUMN local_gov_area.lga_name IS
    'Name of local government area';

COMMENT ON COLUMN local_gov_area.lga_size_ha IS
    'Size of the local government area in hectares';

COMMENT ON COLUMN local_gov_area.lga_ceo_name IS
    'Full name of the local government area''s CEO';

COMMENT ON COLUMN local_gov_area.lga_bf_phoneno IS
    'Local government area bushfire emergency contact number';

ALTER TABLE local_gov_area ADD CONSTRAINT local_gov_area_pk PRIMARY KEY ( lga_code );

CREATE TABLE owner (
    own_id       NUMBER(6) NOT NULL,
    own_name     VARCHAR2(50) NOT NULL,
    own_phoneno  VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN owner.own_id IS
    'Unique number identifier of owners';

COMMENT ON COLUMN owner.own_name IS
    'Full name of owner (could be individual, business, or body corporate)';

COMMENT ON COLUMN owner.own_phoneno IS
    'Phone number of owner; max 15 characters to account for international numbers';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( own_id );

CREATE TABLE property (
    prop_id        NUMBER(8) NOT NULL,
    prop_street    VARCHAR2(30) NOT NULL,
    prop_town      VARCHAR2(20) NOT NULL,
    prop_postcode  CHAR(4) NOT NULL,
    prop_size_ha   NUMBER(9, 2),
    own_id         NUMBER(6) NOT NULL,
    lga_code       NUMBER(3) NOT NULL,
    pt_id          NUMBER(3) NOT NULL
);

COMMENT ON COLUMN property.prop_id IS
    'Unique national property ID';

COMMENT ON COLUMN property.prop_street IS
    'Street component of property address';

COMMENT ON COLUMN property.prop_town IS
    'Town component of property address';

COMMENT ON COLUMN property.prop_postcode IS
    'Postcode component of property address';

COMMENT ON COLUMN property.prop_size_ha IS
    'The size of the property in hectares';

COMMENT ON COLUMN property.own_id IS
    'Unique number identifier of owners';

COMMENT ON COLUMN property.lga_code IS
    'Unique code identifying a local government area';

COMMENT ON COLUMN property.pt_id IS
    'Unique numerical identifer of property type';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_id );

CREATE TABLE property_type (
    pt_id    NUMBER(3) NOT NULL,
    pt_desc  VARCHAR2(20)
);

COMMENT ON COLUMN property_type.pt_id IS
    'Unique numerical identifer of property type';

COMMENT ON COLUMN property_type.pt_desc IS
    'Description of the property type';

ALTER TABLE property_type ADD CONSTRAINT property_type_pk PRIMARY KEY ( pt_id );

ALTER TABLE ass_emp_history
    ADD CONSTRAINT ass_history FOREIGN KEY ( ass_id )
        REFERENCES assessor ( ass_id );

ALTER TABLE fe_build_damage
    ADD CONSTRAINT assign_assessor FOREIGN KEY ( ass_id )
        REFERENCES assessor ( ass_id );

ALTER TABLE fe_build_damage
    ADD CONSTRAINT build_damage FOREIGN KEY ( build_id )
        REFERENCES building ( build_id );

ALTER TABLE build_dam_visit
    ADD CONSTRAINT build_visits FOREIGN KEY ( febd_id )
        REFERENCES fe_build_damage ( febd_id );

ALTER TABLE fe_build_damage
    ADD CONSTRAINT fe_damage FOREIGN KEY ( fe_id )
        REFERENCES fire_event ( fe_id );

ALTER TABLE lga_fe
    ADD CONSTRAINT fe_lga FOREIGN KEY ( fe_id )
        REFERENCES fire_event ( fe_id );

ALTER TABLE fire_event
    ADD CONSTRAINT fire_event_starts FOREIGN KEY ( fe_started_from )
        REFERENCES fire_event ( fe_id );

ALTER TABLE ass_emp_history
    ADD CONSTRAINT ins_emp_history FOREIGN KEY ( ins_code )
        REFERENCES insurer ( ins_code );

ALTER TABLE assessor
    ADD CONSTRAINT ins_employment FOREIGN KEY ( curr_ins_code )
        REFERENCES insurer ( ins_code );

ALTER TABLE building
    ADD CONSTRAINT insurer_building FOREIGN KEY ( ins_code )
        REFERENCES insurer ( ins_code );

ALTER TABLE lga_fe
    ADD CONSTRAINT lga_fire FOREIGN KEY ( lga_code )
        REFERENCES local_gov_area ( lga_code );

ALTER TABLE property
    ADD CONSTRAINT lga_property FOREIGN KEY ( lga_code )
        REFERENCES local_gov_area ( lga_code );

ALTER TABLE property
    ADD CONSTRAINT owner_property FOREIGN KEY ( own_id )
        REFERENCES owner ( own_id );

ALTER TABLE building
    ADD CONSTRAINT prop_build FOREIGN KEY ( prop_id )
        REFERENCES property ( prop_id );

ALTER TABLE property
    ADD CONSTRAINT property_type FOREIGN KEY ( pt_id )
        REFERENCES property_type ( pt_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF